version: '3.8'

services:
  web:
    image: rails-docker
    entrypoint: /rails/bin/docker-entrypoint
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_DOCKER_DATABASE_USERNAME: ${RAILS_DOCKER_DATABASE_USERNAME}
      RAILS_DOCKER_DATABASE_PASSWORD: ${RAILS_DOCKER_DATABASE_PASSWORD}
      RAILS_DOCKER_DATABASE_HOST: db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${RAILS_DOCKER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${RAILS_DOCKER_DATABASE_PASSWORD}