version: '3.8'

x-defaults:
  &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3

services:
  web:
    image: rails-docker
    entrypoint: /rails/bin/docker-entrypoint
    command: rails server -p 4000 -b '0.0.0.0'
    volumes:
      - .:/docker
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      RAILS_DOCKER_DATABASE_USERNAME: ${RAILS_DOCKER_DATABASE_USERNAME}
      RAILS_DOCKER_DATABASE_PASSWORD: ${RAILS_DOCKER_DATABASE_PASSWORD}
      RAILS_DOCKER_DATABASE_HOST: db
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "-O",
          "-",
          "http://localhost:4000"
        ]
      <<: *default-healthcheck

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${RAILS_DOCKER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${RAILS_DOCKER_DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      <<: *default-healthcheck

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "-O",
          "-",
          "http://localhost:9090"
        ]
      <<: *default-healthcheck

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "-O",
          "-",
          "http://localhost:3000"
        ]
      <<: *default-healthcheck
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
