default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['RAILS_DOCKER_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DOCKER_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DOCKER_DATABASE_HOST'] %>

development:
  <<: *default
  database: rails_docker_development

test:
  <<: *default
  database: rails_docker_test

production:
  <<: *default
  database: rails_docker_production
